
import { HabitCategory, Language } from './types';

export const CATEGORIES: HabitCategory[] = [
  'Health',
  'Productivity',
  'Mindfulness',
  'Learning',
  'Social',
  'Other'
];

export const CATEGORY_COLORS: Record<HabitCategory, string> = {
  Health: 'bg-emerald-100 text-emerald-800 border-emerald-200 dark:bg-emerald-500/10 dark:text-emerald-400 dark:border-emerald-500/20',
  Productivity: 'bg-blue-100 text-blue-800 border-blue-200 dark:bg-blue-500/10 dark:text-blue-400 dark:border-blue-500/20',
  Mindfulness: 'bg-purple-100 text-purple-800 border-purple-200 dark:bg-purple-500/10 dark:text-purple-400 dark:border-purple-500/20',
  Learning: 'bg-amber-100 text-amber-800 border-amber-200 dark:bg-amber-500/10 dark:text-amber-400 dark:border-amber-500/20',
  Social: 'bg-rose-100 text-rose-800 border-rose-200 dark:bg-rose-500/10 dark:text-rose-400 dark:border-rose-500/20',
  Other: 'bg-slate-100 text-slate-800 border-slate-200 dark:bg-slate-700/50 dark:text-slate-300 dark:border-slate-600',
};

export const DEFAULT_HABITS = [
  {
    id: '1',
    title: 'Drink 2L Water',
    category: 'Health',
    color: 'emerald',
    createdAt: new Date().toISOString(),
    logs: {}
  },
  {
    id: '2',
    title: 'Read 15 mins',
    category: 'Learning',
    color: 'amber',
    createdAt: new Date().toISOString(),
    logs: {}
  }
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    app_name: 'Yuuhi Tracker',
    weekly_focus: 'Weekly Focus',
    performance: 'Performance',
    profile: 'Profile',
    stats: 'Statistics',
    diary: 'Diary',
    tasks: 'Tasks',
    settings: 'Settings',
    admin: 'Admin',
    new_habit: 'New Habit',
    track_desc: 'Track your consistency day by day.',
    analyze_desc: 'Analyze your long-term progress.',
    manage_desc: 'Manage your account and data.',
    diary_desc: 'Reflect on your days.',
    tasks_desc: 'Manage your daily to-dos.',
    admin_desc: 'Manage users and system settings.',
    habit_title: 'Habit Title',
    category: 'Category',
    create: 'Create Habit',
    cancel: 'Cancel',
    delete_confirm: 'Are you sure?',
    total_completions: 'Total Completions',
    active_habits: 'Active Habits',
    completion_rate: 'Completion Rate (Today)',
    weekly_progress: 'Weekly Progress',
    no_habits: 'No habits yet. Add one to start tracking!',
    login: 'Login',
    create_account: 'Create Account',
    username: 'Username',
    password: 'Password',
    display_name: 'Display Name',
    remember_me: 'Remember me on this device',
    sign_in: 'Sign In',
    sign_up: 'Sign Up',
    have_account: 'Already have an account?',
    need_account: "Don't have an account?",
    welcome_back: 'Welcome Back',
    get_started: 'Get Started',
    logout: 'Logout',
    theme: 'Theme',
    language: 'Language',
    clear_data: 'Clear All Data',
    reset_app: 'Reset App',
    backup_data: 'Backup Data',
    restore_data: 'Restore Data',
    download_backup: 'Download Backup',
    select_file: 'Select File',
    streak: 'streak',
    day: 'day',
    habit_placeholder: 'e.g., Meditate for 10 mins',
    local_management: 'Data Management',
    local_management_desc: 'Manage your data locally.',
    danger_zone: 'Danger Zone',
    delete_all_desc: 'Permanently delete all habits.',
    guest: 'Guest',
    users_list: 'Users List',
    total_users: 'Total Users',
    actions: 'Actions',
    delete_user: 'Delete User',
    delete_user_confirm: 'Are you sure you want to delete this user and ALL their data? This cannot be undone.',
    save_entry: 'Save Entry',
    todays_mood: "Today's Mood",
    write_diary: 'Write about this day...',
    no_entries: 'No diary entries yet.',
    add_task: 'Add a new task...',
    no_tasks: 'No tasks yet. Stay productive!',
    calendar: 'Calendar'
  },
  ja: {
    app_name: '夕日トラッカー',
    weekly_focus: '今週のフォーカス',
    performance: 'パフォーマンス',
    profile: 'プロフィール',
    stats: '統計',
    diary: '日記',
    tasks: 'タスク',
    settings: '設定',
    admin: '管理',
    new_habit: '新しい習慣',
    track_desc: '日々の継続を記録しましょう。',
    analyze_desc: '長期的な進捗を分析します。',
    manage_desc: 'アカウントとデータを管理します。',
    diary_desc: '日々の振り返り。',
    tasks_desc: '毎日のToDoを管理します。',
    admin_desc: 'ユーザーとシステム設定を管理します。',
    habit_title: '習慣のタイトル',
    category: 'カテゴリー',
    create: '作成する',
    cancel: 'キャンセル',
    delete_confirm: '本当によろしいですか？',
    total_completions: '総完了数',
    active_habits: 'アクティブな習慣',
    completion_rate: '完了率 (今日)',
    weekly_progress: '週間進捗',
    no_habits: '習慣がありません。追加して追跡を開始しましょう！',
    login: 'ログイン',
    create_account: 'アカウント作成',
    username: 'ユーザー名',
    password: 'パスワード',
    display_name: '表示名',
    remember_me: 'このデバイスに記憶させる',
    sign_in: 'サインイン',
    sign_up: '登録する',
    have_account: 'すでにアカウントをお持ちですか？',
    need_account: 'アカウントをお持ちでないですか？',
    welcome_back: 'おかえりなさい',
    get_started: 'はじめよう',
    logout: 'ログアウト',
    theme: 'テーマ',
    language: '言語',
    clear_data: '全データを消去',
    reset_app: 'リセット',
    backup_data: 'バックアップ',
    restore_data: '復元',
    download_backup: 'ダウンロード',
    select_file: 'ファイルを選択',
    streak: '日連続',
    day: '日',
    habit_placeholder: '例: 10分間瞑想する',
    local_management: 'データ管理',
    local_management_desc: 'ローカルデータを管理します。',
    danger_zone: '危険エリア',
    delete_all_desc: 'すべての習慣を完全に削除します。',
    guest: 'ゲスト',
    users_list: 'ユーザーリスト',
    total_users: '総ユーザー数',
    actions: '操作',
    delete_user: 'ユーザーを削除',
    delete_user_confirm: 'このユーザーとすべてのデータを削除してもよろしいですか？この操作は取り消せません。',
    save_entry: '保存',
    todays_mood: '今日の気分',
    write_diary: '今日について書く...',
    no_entries: '日記のエントリーはまだありません。',
    add_task: '新しいタスクを追加...',
    no_tasks: 'タスクはまだありません。',
    calendar: 'カレンダー'
  }
};